oncokb/oncokb.yaml

Signed-off-by: Hongxin Zhang <hongxin@cbio.mskcc.org>

Update oncokb version

---

oncokb/oncokb.yaml
oncokb/oncokb_test.yaml

This seems required for the version 8.0

Include --proxy-base-url

---

oncokb/oncokb.yaml

Signed-off-by: Hongxin Zhang <jackson.zhang.828@gmail.com>

Upgrade oncokb to 1.0.2

---

oncokb/oncokb.yaml

Signed-off-by: Hongxin Zhang <hongxin@cbio.mskcc.org>

update oncokb version to 1.0.4

---

oncokb/oncokb.yaml

Signed-off-by: Hongxin Zhang <hongxin@cbio.mskcc.org>

Update oncokb configs

---

cbioportal/cbioportal_backend_master.yaml
ingress/ingress.yml

Should always run latest master backend

Add master.cbioportal.org env

---

cbioportal/cbioportal_backend_genie.yaml
ingress/ingress.yml

Add genie public portal (https://genie-beta.cbioportal.org)
- use tcp probe for now until https://github.com/cBioPortal/cbioportal/issues/5326 is resolved

add genie public config

---

cronjob/oncokb_daily_backup_public_website_db.yaml

Signed-off-by: Hongxin Zhang <hongxin@cbio.mskcc.org>

update namespace for oncokb cronjob

---

cbioportal/cbioportal_backend_genie_private.yaml
cbioportal/cbioportal_backend_genie_public.yaml
ingress/ingress.yml

For two portals
- genie (genie-private) `(cbioportal_backend_genie.yml)`
- genie-public `(cbioportal_backend_genie_public.yml)`
currently mapped to "beta" host names inside ingress
TODO: change to non-beta hostnames once testing is finished

Update/add configs for two genie instances DO NOT MERGE

---

oncokb/oncokb_public.yaml

Fix the swagger redirect to oncokb-core issue

Upgrade OncoKB-public to 2.1.4

---

genome-nexus/gn_genie.yaml
genome-nexus/vep/genie_gn_vep.yaml
genome-nexus/vep/gn_vep_pv.yaml
genome-nexus/vep/gn_vep_pvc.yaml

- Added PV + PVC for VEP cache
- New arguments/images for genome-nexus server

Config Updates for GENIE

---

genome-nexus/README.md

Added section for GENIE Deployment
- Creating PVCs
- Mongo Behavior (persistence + mongodump)
- S3 Bucket/VEP Cache behavior

Updated docs with Internal GENIE Deployment Steps

---

cbioportal/cbioportal_backend_genie_public.yaml

Added email confirmation text to "first time users" registration blurb.
Signed-off-by: Angelica Ochoa <15623749+ao508@users.noreply.github.com>

Update GENIE public login page message.

---

cronjob/genie_gn_weekly_mongodump.yaml
cronjob/gn_weekly_mongodump.yaml
cronjob/gnap_gn_weekly_mongodump.yaml

- check if mongodump actually succeeds 
- send slack message if not
- also added a delete rule in s3 bucket to remove expired dumps
- also updated configs in mercurial

Mongodump Checks

---

oncokb/clinical_trials_matching.yml

update yml file

---

genome-nexus/gn_genie.yaml
genome-nexus/gn_gnap.yaml
genome-nexus/gn_spring_boot.yaml

Signed-off-by: Angelica Ochoa <15623749+ao508@users.noreply.github.com>

Update Genome Nexus docker image tag

---

cronjob/oncokb/oncokb_clinical_trials_matching_pipeline_daily.yaml
cronjob/oncokb/oncokb_usage_analysis_pipeline_daily.yaml

1. Upgrade clinical trials matching pipeline image version
2. Add cronjob yaml for oncokb usage analysis

Upgrade image version and add new yaml

---

cbioportal/cbioportal_backend_jprofiler_agent.yaml
jprofiler-agent/README.md
jprofiler-agent/jprofiler-client-dockerfile

Includes README.md with description.

Files/docs for JProfiling cbioportal backend on k8s

---

cbioportal/cbioportal_backend_genie_private.yaml
cbioportal/cbioportal_backend_genie_private_beta.yaml
cbioportal/cbioportal_backend_genie_public.yaml

Part of: https://github.com/cBioPortal/cbioportal/issues/9413
Update configuration for:
- cbioportal_backend_genie_private.yaml
- cbioportal_backend_genie_private_beta.yaml
- cbioportal_backend_genie_public.yaml

Add NA terms to genie portals

---

genome-nexus/gn_spring_boot.yaml
genome-nexus/gn_spring_boot_grch38.yaml

spring boot : v1.1.47
database: grch37: v0.21; grch38: v0.23

Update genome nexus version for grch37 and grch38

---

digits-eks/eks-prod/shared-services/cdd/cdd-eks-deployment-service.yaml
digits-eks/eks-prod/shared-services/oncotree/oncotree-eks-deployment-service.yaml

* Filename of trust store changed
* Updated CDD docker image

Added topbraid certificate to aws trust store

---

cbioportal/cbioportal_backend_beta.yaml
cbioportal/cbioportal_backend_genie_private.yaml
cbioportal/cbioportal_backend_genie_public.yaml
cbioportal/cbioportal_backend_master.yaml
cbioportal/cbioportal_spring_boot.yaml
digits-eks/eks-prod/cbioportal-eks-msk-beta-deployment-service.yaml
digits-eks/eks-prod/cbioportal-eks-msk-deployment-service.yaml
digits-eks/eks-prod/cbioportal-eks-private-deployment-service.yaml
digits-eks/eks-prod/cbioportal-eks-sclc-deployment-service.yaml
digits-eks/eks-prod/cbioportal-eks-triage-deployment-service.yaml
digits-eks/eks-prod/old/dremio-prototype-deployment-from-public.yaml

Part of: https://github.com/genome-nexus/genome-nexus/issues/634

Add mutation assessor to genome nexus sources

---

oncokb/oncokb-msk/ingress/ingress_oncokb.yaml
oncokb/oncokb-msk/oncokb_cluster_redis_values.yaml
oncokb/oncokb-msk/oncokb_core_beta.yaml
oncokb/oncokb-msk/oncokb_core_beta_cluster.yaml
oncokb/oncokb-msk/oncokb_test.yaml

Add additional deployment files and redis-cluster values file

Add deployment files used in MSK Dev Cluster

---

oncokb/airflow/README.md
oncokb/airflow/oncokb_airflow_service_account.yaml
oncokb/airflow/oncokb_airflow_serviceaccount.yaml
oncokb/airflow/oncokb_airflow_values.yaml

This fixes https://github.com/oncokb/oncokb/issues/3329

Create oncokb airflow service account and add airflow helm chart values

---

oncokb/oncokb_redis_cluster_values.yaml

This is fixes https://github.com/oncokb/oncokb/issues/3330

Increase OncoKB Redis Cluster Replica Nodes Count to 2

---

ingress/ingress_oncokb.yml
oncokb/airflow/README.md
oncokb/airflow/oncokb_airflow_values.yaml

This fixes https://github.com/oncokb/oncokb/issues/3357

Update oncokb airflow deployment

---

oncokb/HELM_DEPLOYMENTS.md

Add oncokb helm chart versions and general informaation

Add readme for oncokb helm usage

---

public-eks/cbioportal-prod/cbioportal_backend_beta.yaml
public-eks/cbioportal-prod/cbioportal_spring_boot.yaml
public-eks/cbioportal-prod/shared-services/ingress/cbio-ingress.yml

Deployments:
- public portal
- public portal beta
Ingress:
- public portal
- public portal beta

Move public cbioportal and beta cbioportal to public eks

---

oncokb/HELM_DEPLOYMENTS.md
oncokb/elasticsearch/elasticsearch-config.yaml
oncokb/oncokb-prod/ingress_oncokb.yml
oncokb/shared/airflow/oncokb_airflow_values.yaml
public-eks/cbioportal-prod/shared-services/ingress/oncokb_cert.yaml

Move oncokb-curation, oncokb-keycloak, oncokb-airflow and oncokb-elasticsearch to cbioportal-prod cluster

Move remaining OncoKB apps to cbioportal-prod cluster

---

oncokb/shared/airflow/oncokb_airflow_requirements.yaml

This resolves the import errors in OncoKB airflow

Update airflow requirements

---

oncokb/keycloak/keycloak-config.yaml
oncokb/oncokb-eu/oncokb_core.yaml
oncokb/oncokb-eu/oncokb_public.yaml
oncokb/oncokb-msk/prod/oncokb_core.yaml
oncokb/oncokb-msk/prod/oncokb_core_cbx.yaml
oncokb/oncokb-prod/data_versioned/oncokb_core_data_3_11.yaml
oncokb/oncokb-prod/data_versioned/oncokb_core_data_4_0.yaml
oncokb/oncokb-prod/data_versioned/oncokb_core_data_4_5.yaml
oncokb/oncokb-prod/data_versioned/oncokb_core_data_4_9.yaml
oncokb/oncokb-prod/data_versioned/oncokb_public_data_3_11.yaml
oncokb/oncokb-prod/data_versioned/oncokb_public_data_4_0.yaml
oncokb/oncokb-prod/data_versioned/oncokb_public_data_4_5.yaml
oncokb/oncokb-prod/data_versioned/oncokb_public_data_4_9.yaml
oncokb/oncokb-prod/ingress_oncokb.yml
oncokb/oncokb-prod/oncokb_core.yaml
oncokb/oncokb-prod/oncokb_core_beta.yaml
oncokb/oncokb-prod/oncokb_core_demo.yaml
oncokb/oncokb-prod/oncokb_core_public.yaml
oncokb/oncokb-prod/oncokb_curation.yaml
oncokb/oncokb-prod/oncokb_curation_beta.yaml
oncokb/oncokb-prod/oncokb_public.yaml
oncokb/oncokb-prod/oncokb_public_beta.yaml
oncokb/oncokb-prod/oncokb_sop.yaml
oncokb/oncokb-prod/oncokb_transcript.yaml
oncokb/oncokb-prod/oncokb_transcript_beta.yaml
oncokb/oncokb.dev/ingress_oncokb_dev.yml
oncokb/shared/airflow/oncokb_airflow_values.yaml
oncokb/shared/redis/oncokb_curation_redis_values.yaml
oncokb/shared/redis/oncokb_redis_cluster_values.yaml
public-eks/cbioportal-prod/shared-services/ingress/oncokb_cert.yaml

This is related to https://github.com/oncokb/oncokb-pipeline/issues/185

Update oncokb instances for V2 account migration

---

cronjob/oncokb/oncokb_daily_backup_token_stats.yaml
oncokb/shared/airflow/oncokb_airflow_service_account.yaml

This is related to https://github.com/oncokb/oncokb-pipeline/issues/210

Update oncokb cronjob to new schultz lab account

---

genome-nexus/README.md

Update command for creating mongodb

---

public-eks/cbioportal-prod/cellxgene/README.md
public-eks/cbioportal-prod/cellxgene/cellxgene-deployment.yaml
public-eks/cbioportal-prod/cellxgene/cellxgene-ingress.yaml

This adds new GBM datasets to cellxgene.cbioportal.org

Add btc gbm cellxgene instances

---

oncokb/oncokb-prod/ingress_oncokb.yml
oncokb/oncokb-prod/oncokb_curation.yaml
oncokb/oncokb-prod/oncokb_curation_beta.yaml

update curation platform with new image and create pod for new keycloak version

update to use new keycloak version

---

digits-eks/eks-prod/cbioportal-eks-msk-nci-deployment-service.yaml
ingress/ingress.yml

This PR adds the deployment service file for crdc.cbioportal.org according to what's currently deployed on the cluster. I also modified the ingress rules for the new subdomain. cc: @inodb

Add NCI deployment file & modify Ingress rules

---

digits-eks/eks-prod/shared-services/oncotree/oncotree-eks-deployment-service.yaml

mainly new image + new startup command

updated deployment for graphite-backed oncotree

---

digits-eks/eks-prod/shared-services/cdd/cdd-eks-deployment-service.yaml
digits-eks/eks-prod/shared-services/cdd/cdd-pvc.yaml

switch to graphite (synaptica)
new image pushed to dockerhub

updated configurations for cdd

---

genome-nexus/gn_spring_boot.yaml
genome-nexus/gn_spring_boot_beta.yaml

Deploy Mutation assessor v4 in genome nexus

Deploy genome nexus

---

oncokb/oncokb-msk/dev/api-load-testing/README.md
oncokb/oncokb-msk/dev/api-load-testing/eksctl-nodegroup-config.yaml
oncokb/oncokb-msk/dev/api-load-testing/gn_mongo_values.yaml
oncokb/oncokb-msk/dev/api-load-testing/gn_spring_boot.yaml
oncokb/oncokb-msk/dev/api-load-testing/oncokb_core.yaml
oncokb/oncokb-msk/dev/api-load-testing/oncokb_public.yaml
oncokb/oncokb-msk/dev/api-load-testing/oncokb_redis_cluster_values.yaml
oncokb/oncokb-msk/dev/ingress_oncokb.yaml

Related to https://github.com/oncokb/oncokb-pipeline/issues/553

Add deployment files for oncokb performance tests

---

public-eks/cbioportal-prod/cbioportal_backend_genie_private_blue.yaml
public-eks/cbioportal-prod/cbioportal_backend_genie_private_green.yaml
public-eks/cbioportal-prod/cbioportal_backend_genie_public_beta_blue.yaml
public-eks/cbioportal-prod/cbioportal_backend_genie_public_beta_green.yaml
public-eks/cbioportal-prod/cbioportal_backend_genie_public_blue.yaml
public-eks/cbioportal-prod/cbioportal_backend_genie_public_green.yaml

adjust genie replica counts to match prod

---

digits-eks/eks-prod/cbioportal-eks-msk-rfc80-deployment-service.yaml
digits-eks/eks-prod/cbioportal-eks-triage-deployment-service.yaml

Update certificate for triage portal and upload uncommitted changes for rfc80 portal

Update certificate for triage portal and upload rfc80 portal updates

---

public-eks/cbioportal-prod/cellxgene/cellxgene-configmap.yaml
public-eks/cbioportal-prod/cellxgene/cellxgene-index-deployment.yaml
public-eks/cbioportal-prod/cellxgene/cellxgene-ingress.yaml

Adding the index page commits here. Will organize more granularly soon.

Add initial index page and corresponding configmap

---

public-eks/cbioportal-prod/cbioportal_backend_genie_private_blue.yaml
public-eks/cbioportal-prod/cbioportal_backend_genie_private_green.yaml
public-eks/cbioportal-prod/cbioportal_backend_genie_public_blue.yaml
public-eks/cbioportal-prod/cbioportal_backend_genie_public_green.yaml

Update genie image to release-6.0.24-alpha-web-shenandoah, we should change to official image after 6.0.24 released

Update genie image

---

oncokb/oncokb-prod/ingress_oncokb.yml
oncokb/oncokb-prod/oncokb_public_staging.yaml
public-eks/cbioportal-prod/shared-services/ingress/oncokb_cert.yaml

resolves https://github.com/oncokb/oncokb-pipeline/issues/652

add deployment for oncokb staging

---

oncokb/oncokb-prod/oncokb_curation.yaml
oncokb/oncokb-prod/oncokb_curation_beta.yaml
oncokb/oncokb-prod/oncokb_public.yaml
oncokb/oncokb-prod/oncokb_sop.yaml

Any issues with [PR](https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/pull/311) for the SOP? (That change is also in this PR)

Curation Update

---

public-eks/cbioportal-prod/shared-services/ingress/cbio-ingress.yml

add public-data.cbioportal.org

---

genome-nexus/gn_spring_boot.yaml
genome-nexus/gn_spring_boot_beta.yaml

Public instance to version 2.0.2

Update GN 

---

oncokb/oncokb-eu/oncokb_core.yaml
oncokb/oncokb-eu/oncokb_public.yaml
oncokb/oncokb-msk/prod/oncokb_core.yaml
oncokb/oncokb-msk/prod/oncokb_core_cbx.yaml
oncokb/oncokb-msk/prod/oncokb_public.yaml
oncokb/oncokb-prod/oncokb_core.yaml
oncokb/oncokb-prod/oncokb_core_beta.yaml
oncokb/oncokb-prod/oncokb_core_curation.yaml
oncokb/oncokb-prod/oncokb_core_demo.yaml
oncokb/oncokb-prod/oncokb_core_public.yaml
oncokb/oncokb-prod/oncokb_public.yaml
oncokb/oncokb-prod/oncokb_public_beta.yaml
oncokb/oncokb-prod/oncokb_public_staging.yaml
oncokb/oncokb-prod/oncokb_sop.yaml

Updated Deployments

---

digits-eks/eks-prod/shared-services/airflow/override-values.yaml

Mount keyfile for connecting to pipelines3 from Airflow server and create connection string

Mount keyfile for connecting to pipelines3 and create connection string

---

argocd/aws/203403084713/clusters/cbioportal-prod/apps/ingress/mosaic-ingress.yml

- creates a new file to contain Mosaic Ingress settings
- removes Mosaic settings from cbio-ingress.yml

Paladin/Mosaic separation from cbioportal Ingress

---

argocd/aws/203403084713/clusters/cbioportal-prod/apps/cbioportal/cbioportal_public_mysqldump_weekly.yaml

- missing semicolons added
- filename string construction bug fixed (for purging old dumps)

bugfixes to public_mysqldump_weekly
